"use client";

import { useEffect, useState } from 'react';
import { useAuthStore } from '@/lib/store';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import Link from 'next/link';
import { Download, FileText, ArrowLeft, BarChart } from 'lucide-react';

export default function StudentReports() {
  const { user, token } = useAuthStore();
  const router = useRouter();

  const [stats, setStats] = useState<any>(null);
  const [members, setMembers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!user || user.role !== 'student') {
      router.push('/login');
      return;
    }

    const loadData = async () => {
      try {
        const opts = { headers: { Authorization: `Bearer ${token}` } };
        const [memRes, statsRes] = await Promise.all([
          axios.get('http://127.0.0.1:8000/api/student/community/members', opts),
          axios.get('http://127.0.0.1:8000/api/student/community/stats', opts)
        ]);
        setMembers(memRes.data);
        setStats(statsRes.data);
      } catch (err: any) {
        setError('Failed to fetch data. Please try again.');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    
    loadData();
  }, [user, token, router]);

  const generatePDF = () => {
    if (!stats || !user) return;
    
    const doc = new (jsPDF as any)();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(20, 40, 80);
    doc.text('CFSS Community Report', 14, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Community ID: ${stats.community_id}`, 14, 30);
    doc.text(`Group Label: ${user.group_number ? `Group ${user.group_number}` : 'Pending Group'}`, 14, 37);
    doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 44);

    // Summary section
    doc.setFontSize(16);
    doc.setTextColor(20, 40, 80);
    doc.text('1. Statistical Summary', 14, 60);
    
    const summaryData = [
      ['Total Surveys Submitted', stats.total_surveys.toString()],
      ['Total Population Surveyed', stats.summary?.household?.population?.toString() || '0'],
      ['Schools Recorded', stats.summary?.education?.schools?.toString() || '0'],
      ['Hospitals/Clinics Recorded', stats.summary?.health?.hospitals?.toString() || '0'],
      ['Water Access Sites Recorded', stats.summary?.governance?.water_access?.toString() || '0']
    ];

    doc.autoTable({
      startY: 65,
      head: [['Metric', 'Value']],
      body: summaryData,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
    });

    // Members section
    const finalY = (doc as any).lastAutoTable.finalY || 65;
    
    doc.setFontSize(16);
    doc.setTextColor(20, 40, 80);
    doc.text('2. Group Members', 14, finalY + 15);
    
    const membersData = members.map(m => [
      m.student_id, 
      m.name, 
      m.program || 'N/A', 
      m.level.toString()
    ]);
    
    doc.autoTable({
      startY: finalY + 20,
      head: [['Student ID', 'Name', 'Program', 'Level']],
      body: membersData,
      theme: 'striped',
      headStyles: { fillColor: [46, 204, 113] },
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(
        `Generated by Community Field Survey System (CFSS) - Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      );
    }
    
    doc.save(`Community_Report_${user.group_number ? `Group_${user.group_number}` : 'Group'}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  if (!user) return null;

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-4xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="bg-white p-6 border border-gray-200 rounded-xl shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center">
          <div className="flex items-center gap-4">
            <Link href="/dashboard" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-lg text-slate-600 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Community Report</h1>
              <p className="text-sm text-gray-500 mt-1">Review your collected data and export PDF.</p>
            </div>
          </div>
          <div className="mt-4 md:mt-0">
            <button 
              onClick={generatePDF}
              disabled={loading || !stats}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium shadow-sm"
            >
              <Download className="w-4 h-4" />
              Download PDF Report
            </button>
          </div>
        </div>

        {error && (
          <div className="p-4 bg-red-50 text-red-700 border border-red-200 rounded-lg">
            {error}
          </div>
        )}

        {loading ? (
          <div className="flex justify-center py-20">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Stats Overview */}
            <div className="md:col-span-2 space-y-6">
              <div className="bg-white p-6 border border-gray-200 rounded-xl shadow-sm">
                <div className="flex items-center gap-2 mb-6 border-b pb-4">
                  <BarChart className="w-5 h-5 text-blue-600" />
                  <h2 className="text-lg font-bold text-gray-900">Statistical Summary</h2>
                </div>
                
                {stats && (
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-100">
                      <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Total Surveys</p>
                      <p className="text-3xl font-bold text-slate-800">{stats.total_surveys}</p>
                    </div>
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-100">
                      <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Total Population</p>
                      <p className="text-3xl font-bold text-slate-800">{stats.summary?.household?.population || 0}</p>
                    </div>
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-100">
                      <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Schools Recorded</p>
                      <p className="text-3xl font-bold text-slate-800">{stats.summary?.education?.schools || 0}</p>
                    </div>
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-100">
                      <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider mb-1">Hospitals Recorded</p>
                      <p className="text-3xl font-bold text-slate-800">{stats.summary?.health?.hospitals || 0}</p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Members List */}
            <div className="md:col-span-1 space-y-6">
              <div className="bg-white p-6 border border-gray-200 rounded-xl shadow-sm">
                <div className="flex items-center gap-2 mb-6 border-b pb-4">
                  <FileText className="w-5 h-5 text-emerald-600" />
                  <h2 className="text-lg font-bold text-gray-900">Group Members</h2>
                </div>
                
                {members.length > 0 ? (
                  <ul className="space-y-3 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                    {members.map(m => (
                      <li key={m.id} className="p-3 border border-slate-100 rounded-lg bg-slate-50 hover:bg-slate-100 transition-colors">
                        <p className="font-semibold text-slate-900">{m.name}</p>
                        <div className="flex items-center justify-between mt-1">
                          <p className="text-xs font-medium text-blue-600">{m.student_id}</p>
                          <p className="text-[10px] bg-slate-200 text-slate-700 px-2 py-0.5 rounded-full">{m.program || 'N/A'}</p>
                        </div>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-sm text-slate-500 text-center py-4">No members found.</p>
                )}
              </div>
            </div>

          </div>
        )}

      </div>
    </div>
  );
}
