"""AddSurveyTables

Revision ID: b16dbcdc0a7c
Revises: c6c66c014fef
Create Date: 2026-07-07 20:47:41.297352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b16dbcdc0a7c'
down_revision: Union[str, Sequence[str], None] = 'c6c66c014fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('survey_type', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_id'), 'survey_questions', ['id'], unique=False)
    op.create_index(op.f('ix_survey_questions_survey_type'), 'survey_questions', ['survey_type'], unique=False)
    op.create_table('survey_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('created_by_student_id', sa.Integer(), nullable=False),
    sa.Column('survey_type', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['created_by_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'survey_type', 'house_number', name='uq_survey_record_house')
    )
    op.create_index(op.f('ix_survey_records_community_id'), 'survey_records', ['community_id'], unique=False)
    op.create_index(op.f('ix_survey_records_created_by_student_id'), 'survey_records', ['created_by_student_id'], unique=False)
    op.create_index(op.f('ix_survey_records_house_number'), 'survey_records', ['house_number'], unique=False)
    op.create_index(op.f('ix_survey_records_id'), 'survey_records', ['id'], unique=False)
    op.create_index(op.f('ix_survey_records_survey_type'), 'survey_records', ['survey_type'], unique=False)
    op.create_table('survey_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('survey_record_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ),
    sa.ForeignKeyConstraint(['survey_record_id'], ['survey_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_answers_id'), 'survey_answers', ['id'], unique=False)
    op.create_index(op.f('ix_survey_answers_survey_record_id'), 'survey_answers', ['survey_record_id'], unique=False)
    op.drop_index(op.f('ix_system_users_email'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_student_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_trace_id'), table_name='system_users')
    op.drop_table('system_users')
    op.alter_column('communities', 'group_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'batch_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('batch_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('communities', 'group_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('system_users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('program', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_users_pkey'))
    )
    op.create_index(op.f('ix_system_users_trace_id'), 'system_users', ['trace_id'], unique=False)
    op.create_index(op.f('ix_system_users_student_id'), 'system_users', ['student_id'], unique=True)
    op.create_index(op.f('ix_system_users_email'), 'system_users', ['email'], unique=True)
    op.drop_index(op.f('ix_survey_answers_survey_record_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_survey_answers_id'), table_name='survey_answers')
    op.drop_table('survey_answers')
    op.drop_index(op.f('ix_survey_records_survey_type'), table_name='survey_records')
    op.drop_index(op.f('ix_survey_records_id'), table_name='survey_records')
    op.drop_index(op.f('ix_survey_records_house_number'), table_name='survey_records')
    op.drop_index(op.f('ix_survey_records_created_by_student_id'), table_name='survey_records')
    op.drop_index(op.f('ix_survey_records_community_id'), table_name='survey_records')
    op.drop_table('survey_records')
    op.drop_index(op.f('ix_survey_questions_survey_type'), table_name='survey_questions')
    op.drop_index(op.f('ix_survey_questions_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    # ### end Alembic commands ###
