"""Add faculty to User and Whitelist

Revision ID: cf5d4da01185
Revises: b16dbcdc0a7c
Create Date: 2026-09-14 20:27:46.980045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5d4da01185'
down_revision: Union[str, Sequence[str], None] = 'b16dbcdc0a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_records_house_number'), table_name='survey_records')
    op.create_index(op.f('ix_survey_records_entity_id'), 'survey_records', ['entity_id'], unique=False)
    op.add_column('users', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('whitelist_entries', sa.Column('faculty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelist_entries', 'faculty')
    op.drop_column('users', 'faculty')
    op.drop_index(op.f('ix_survey_records_entity_id'), table_name='survey_records')
    op.create_index(op.f('ix_survey_records_house_number'), 'survey_records', ['entity_id'], unique=False)
    # ### end Alembic commands ###
