"""add survey_counter and submitted_at

Revision ID: d1e2f3a4b5c6
Revises: c6c66c014fef
Create Date: 2026-09-18 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2f3a4b5c6'
down_revision = 'c6c66c014fef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('survey_type', sa.String(), nullable=False),
    sa.Column('last_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'survey_type', name='uq_survey_counters_comm_type')
    )
    op.create_index(op.f('ix_survey_counters_community_id'), 'survey_counters', ['community_id'], unique=False)
    op.create_index(op.f('ix_survey_counters_id'), 'survey_counters', ['id'], unique=False)
    op.create_index(op.f('ix_survey_counters_survey_type'), 'survey_counters', ['survey_type'], unique=False)
    
    op.add_column('survey_records', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_records', 'submitted_at')
    
    op.drop_index(op.f('ix_survey_counters_survey_type'), table_name='survey_counters')
    op.drop_index(op.f('ix_survey_counters_id'), table_name='survey_counters')
    op.drop_index(op.f('ix_survey_counters_community_id'), table_name='survey_counters')
    op.drop_table('survey_counters')
    # ### end Alembic commands ###
